### ISSUE TITLE
welcome contribution ラベル -> help wanted ラベルへ置換する

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/vuefes-2019#63]
@448jp @yinm @aytdm @ryamakuchi @mtmtkzm @monkick @satotakumi @hisako135 @potato4d CC: @kazupon 

`welcome contribution` ラベルと `help wanted` ラベルは必ずしも同じ意味ではないのですが、用途が重複する場合が多々あり、紛らわしいので、`help wanted` に統一します。

## TODO

- [x] Vue Fes の Web サイト班に周知する
- [x] `welcome contribution` ラベルが付いている Issue に `help wanted` ラベルを付ける
- [x] `welcome contribution` ラベルを削除する
